cart/urls.py
from . import views
from django.urls import path
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetail, name='CartDetail'),
    path('remove/(<product_id>)/', views.CartRemove, name='CartRemove'),
    path('add/(<product_id>)/', views.CartAdd, name='CartAdd'),
]

order/urls.py
from django.urls import path
from order.views import OrderCreate, AdminOrderDetail
from . import views

app_name = 'order'

urlpatterns = [
    path('create/', views.OrderCreate, name='OrderCreate'),
    path('admin/order/<order_id>/', views.AdminOrderDetail, name='AdminOrderDetail'),
    
]

product/urls.py
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from product import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductList, name='ProductList'),
    path('<category_slug>/', views.ProductList, name='ProductListByCategory'),
    path('<slug>', views.ProductDetail, name='ProductDetail'),
]

sto/urls.py
"""
Definition of urls for sto.
"""



from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from datetime import datetime
import app.forms
import app.views
from django.shortcuts import render, redirect
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
     path('', app.views.home, name='home'),
    path('contact/', app.views.contact, name='contact'),
    path('about/', app.views.about, name='about'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('registration/', app.views.registration, name='registration'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('product/', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='order')),
    path('created/', include('order.urls', namespace='created')),
    path('userorders/', app.views.userorders, name='userorders'),
    path('allorders/', app.views.allorders, name='allorders'),
    path('services/', app.views.services, name='services'),
    path('diagnost/', app.views.diagnost, name='diagnost'),
    path('anketa/', app.views.anketa, name='anketa'),
    path('to/', app.views.to, name='to'),
    path('dvs/', app.views.dvs, name='dvs'),
    path('kompl/', app.views.kompl, name='kompl'),
    path('torm/', app.views.torm, name='torm'),
    path('ryl/', app.views.ryl, name='ryl'),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 6)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Количество ")
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from product.models import Product
from django.http import HttpRequest
from .cart import Cart
from datetime import datetime
from .forms import CartAddProductForm


@require_POST
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('cart:CartDetail')

def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')

def CartDetail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                                        initial={
                                            'quantity': item['quantity'],
                                            'update': True
                                        })
    return render(request, 'cart/detail.html',
                 {
                 	'cart': cart,
                 	'year':datetime.now().year,
                 })

cart/templates/cart/detail.html
{% extends "app/layout.html" %}
{% load staticfiles %}
{% block title %}
  Ваша корзина товаров
{% endblock %}

{% block content %}
<div class="impl_bread_wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1>Корзина товаров</h1>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                        <li class="breadcrumb-item active">Корзина товаров</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="impl_sell_wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-md-12 offset-lg-1">
                    <div class="impl_checkout_wrapper" id="impl_sform">
                    	{% if user.is_authenticated %}
                    	{% if cart %}
                        <ul id="step_progressbar">
                            <li class="active"><span>Список товаров</span></li>
                        </ul>
                        <div class="impl_step">
                            <div class="woocommerce">
                                <form>
                                    <table class="table table-bordered shop_table cart">
										<thead>
											<tr>
												<th>Изображение</th>
												<th>Товар</th>
												<th>Количество</th>
												<th>Цена</th>
												<th>Всего</th>
												<th>Удалить</th>
											</tr>
											{% for item in cart %}
        									{% with product=item.product %}
											<tr>
												<td><a href="{{ product.get_absolute_url }}"><img src="{{ product.image.url }}" alt="prod"></a></td>
												<td>{{ product.name }}</td>
												<td>
													{{ item.quantity }} | шт.
												</td>
												<td>{{ item.price }} руб.</td>
												<td>{{ item.total_price }} руб.</td>
												<td><a href="{% url "cart:CartRemove" product.id %}"><span class="cart_rmv_icon"><i class="fa fa-times" aria-hidden="true"></i></span></a></td>
											</tr>
											{% endwith %}
    										{% endfor %}
										</thead>
                                    </table>
                                    <div class="impl_cart_footer">
                                        <div class="cart-subtotals">
                                            <div class="total-line total_amount">
                                                <span class="label">Итого:</span>
                                                <span class="value price">{{ cart.get_total_price|floatformat:"2" }} руб.</span>
                                            </div>
                                        </div>
                                    </div>
                                </form>

                            </div>
                            <a href="{% url "product:ProductList"%}" class="next action-button impl_btn">В магазин</a>
                            {% if cart|length > 0 %}
                            <a href="{% url "order:OrderCreate" %}" class="next action-button impl_btn">Оформить</a>
                            {% endif %}
                        </div>
                        {% else %}
                        <div class="impl_print_rcpt">
                            <h1>Ваша корзина пуста</h1>
                            <p>Перейдите в магазин, чтобы добавить товары в корзину</p>
                            <button class="impl_btn"><a href="{% url 'product:ProductList' %}">В магазин</a></button>
                        </div>
                        {% endif %}
                        {% else %}
                        <div class="impl_print_rcpt">
                            <h1>Корзина не доступна</h1>
                            <p>Для просмотра корзины Вам необходимо авторизоваться на сайте</p>
                            <button class="impl_btn"><a href="{% url 'login' %}">Войти</a></button>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}