blog/urls.py
from django.urls import path  
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
  
app_name = 'blog'  
  
urlpatterns = [  
    path('', views.blog, name='blog'),
    path('<id>/', views.blogpost, name='blogpost'),
    path('newpost', views.newpost, name='newpost'),
]

if settings.DEBUG:
    if settings.MEDIA_ROOT:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

sto/urls.py
"""
Definition of urls for sto.
"""



from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from datetime import datetime
import app.forms
import app.views
from django.shortcuts import render, redirect
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
     path('', app.views.home, name='home'),
    path('contact/', app.views.contact, name='contact'),
    path('about/', app.views.about, name='about'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('registration/', app.views.registration, name='registration'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('product/', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='order')),
    path('created/', include('order.urls', namespace='created')),
    path('userorders/', app.views.userorders, name='userorders'),
    path('allorders/', app.views.allorders, name='allorders'),
    path('services/', app.views.services, name='services'),
    path('diagnost/', app.views.diagnost, name='diagnost'),
    path('anketa/', app.views.anketa, name='anketa'),
    path('to/', app.views.to, name='to'),
    path('dvs/', app.views.dvs, name='dvs'),
    path('kompl/', app.views.kompl, name='kompl'),
    path('torm/', app.views.torm, name='torm'),
    path('ryl/', app.views.ryl, name='ryl'),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

blog/models.py
from django.db import models
from django.contrib import admin
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

#модель данных блога
class Blog(models.Model):
    title = models.CharField(max_length = 100, unique_for_date = "posted", verbose_name = "Заголовок")
    author = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name = "Автор")
    description = models.TextField(verbose_name = "Краткое содержание")
    content = models.TextField(verbose_name = "Полное содержание")
    posted = models.DateTimeField(default = timezone.now, db_index = True, verbose_name = "Опубликована")
    image = models.FileField(default = 'temp.jpg', verbose_name = "Путь к картинке")
    def get_absolute_url(self): # метод возвращает строку с URL-адресом записи
        return reverse('blog:blogpost', args=[self.id])

    def __str__(self): # метод возвращает название, используемое для представления отдельных записей в административном разделе
        return self.title
    class Meta:
        db_table = "Posts" # имя таблицы для модели
        ordering = ["-posted"] # порядок сортировки данных в модели ("-" означает по убыванию)
        verbose_name = "статья блога" # имя, под которым модель будет отображаться в административном разделе (для одной статьи блога)
        verbose_name_plural = "статьи блога" # тоже для всех статей блога
       
 
admin.site.register(Blog)

#модель комментариев
class Comment(models.Model):
    text = models.TextField(verbose_name = "Комментарий")
    date = models.DateTimeField(default = timezone.now, db_index = True, verbose_name = "Дата")
    author = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name = "Автор")
    post = models.ForeignKey(Blog, on_delete = models.CASCADE, verbose_name = "Статья")
    
    def __str__(self): # метод возвращает название, используемое для представления отдельных записей в административном разделе
        return 'Комментарий %s к %s' % (self.author, self.post)
    
    class Meta:
        db_table = "Comments" # имя таблицы для модели
        verbose_name = "Комментарий" # имя, под которым модель будет отображаться в административном разделе (для одной статьи блога)
        verbose_name_plural = "Комментарии к статьям блога" # тоже для всех статей блога
        ordering = ["-date"] # порядок сортировки данных в модели ("-" означает по убыванию)

admin.site.register(Comment)

blog/forms.py
from django import forms
from .models import Comment
from django.db import models
from .models import Blog

class CommentForm (forms.ModelForm):
    class Meta:
        model = Comment # используемая модель
        fields = ('text',) # требуется заполнить только поле text
        labels = {'text': "Комментарий"} # метка к полю формы text
        
class BlogForm (forms.ModelForm):
    image = forms.FileField(label="Изображение")
    title = forms.CharField(label="Заголовок новости", widget=forms.TextInput(attrs={'class':'form-control require', 'placeholder':'Заголовок'}))
    description = forms.CharField(label="Краткое описание", widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Краткое описание'}))
    content = forms.CharField(label="Полное содержание", widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Полное содержание'}))
    class Meta:
        model = Blog #используемая модель
        fields = ('title', 'description', 'content', 'posted', 'author', 'image',)
        labels = {'title':"Заголовок",'description':"Краткое описание", 'content':"Содержание", 'posted':"Дата", 'author':"Автор", 'image':"Изображение",}

blog/views.py
from django.shortcuts import render, redirect
from blog.models import Blog, Comment
from blog.forms import CommentForm, BlogForm
from django.http import HttpRequest
from django.template import RequestContext
from datetime import datetime

def blog(request):
    """Renders the blog page."""
    last = Blog.objects.order_by('-posted')[:3]
    assert isinstance(request, HttpRequest)
    posts = Blog.objects.all() # запрос на выбор всех статей блога из модели
    return render(
        request,
        'blog/blog.html',
        {
        'title':'Блог',
        'last': last,
        'posts': posts, # передача списка статей в шаблон веб-страницы
        'year':datetime.now().year,
        }

)

def blogpost(request, id):
    last = Blog.objects.order_by('-posted')[:3]
    post_1 = Blog.objects.get(id=id) # запрос на выбор конкретной статьи по параметру
    comments = Comment.objects.filter(post=id)
    if request.method == "POST": # после отправки данных формы на сервер методом POST
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_f = form.save(commit=False)
            comment_f.author = request.user # добавляем (так как этого поля нет в форме) в модель Комментария (Comment) в поле автор авторизованного пользователя
            comment_f.date = datetime.now() # добавляем в модель Комментария (Comment) текущую дату
            comment_f.post = Blog.objects.get(id=id) # добавляем в модель Комментария (Comment) статью, для которой данный комментарий
            comment_f.save() # сохраняем изменения после добавления полей
            return redirect('blog:blogpost', id=id) # переадресация на ту же страницу статьи после отправки комментария
    else:
        form = CommentForm() # создание формы для ввода комментария
    return render(
        request,
        'blog/blogpost.html',
        {
        	'last': last,
            'post_1': post_1, # передача конкретной статьи в шаблон веб-страницы
            'comments': comments, # передача всех комментариев к данной статье в шаблон веб-страницы
            'form': form, # передача формы добавления комментария в шаблон веб-страницы
            'year':datetime.now().year,
        }
)

def newpost(request):
    """Renders the newpost page."""
    last = Blog.objects.order_by('-posted')[:3]
    if request.method == "POST":                        #после отправки формы
        blogform = BlogForm(request.POST, request.FILES)
        if blogform.is_valid():
            blog_f = blogform.save(commit=False)
            blog_f.posted = datetime.now()
            blog_f.save()
            return redirect('blog')
    else:
        blogform = BlogForm()

    assert isinstance(request, HttpRequest)
    return render(
        request,
        'blog/newpost.html',
        {
            'blogform': blogform,
            'last': last,
            'year': datetime.now().year,
        }
    )

blog/templates/blog/blog.html
{% extends "app/layout.html" %}
{% load staticfiles %}
{% block content %}
<div class="impl_bread_wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1>{{ title }}</h1>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                        <li class="breadcrumb-item active">Блог</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!------ Blog section Start ------>
    <div class="impl_blog_wrapper impl_blog_page">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="impl_blog_inner">
                        <div class="row">
                            <div class="col-lg-3 col-md-3">
                                <div class="impl_sidebar">
                                    <div class="widget widget_recent_entries">
                                        <h2 class="widget-title">Последние посты</h2>
                                        <ul>
                                        	{% for l in last %}
                                            <li>
                                                <div class="recent_cmnt_img">
                                                    <img src="{{ l.image.url }}" alt="pic">
                                                </div>
                                                <div class="recent_cmnt_data">
                                                    <h4><a href="{{ l.get_absolute_url }}">{{ l.title }}</a></h4>
                                                    <span>{{ l.posted | date }}</span>
                                                </div>
                                            </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-9 col-md-9 impl_blog_section">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12">
                                    	{% for post in posts %}
                                        <div class="impl_blog_box">
                                            <div class="impl_post_img">
                                                <img src="{{ post.image.url }}" alt="post" class="img-fluid" />
                                                <span class="impl_pst_date">
										{{ post.posted | date | truncatechars:9 }}
									</span>
                                            </div>
                                            <div class="impl_post_data">
                                                <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                                                <p>{{ post.description }}</p>
                                                <div class="impl_pst_info">
                                                    <div class="impl_pst_admin">
                                                        <span>{{ post.author }} | </span>
                                                        <span>{{ post.posted | date }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blogpost.html
{% extends "app/layout.html" %}
{% load staticfiles %}
{% block content %}
<div class="impl_bread_wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1>{{post_1.title}}</h1>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'blog:blog' %}">Блог</a></li>
                        <li class="breadcrumb-item active">пост № {{ post_1.id }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <!------ Blog section Start ------>
    <div class="impl_blog_wrapper impl_blog_page">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="impl_blog_inner">
                        <div class="row">
                            <div class="col-lg-3 col-md-3">
                                <div class="impl_sidebar">
                                    <div class="widget widget_recent_entries">
                                        <h2 class="widget-title">Недавние посты</h2>
                                        <ul>
                                        	{% for l in last %}
                                            <li>
                                                <div class="recent_cmnt_img">
                                                    <img src="{{ l.image.url }}" alt="last">
                                                </div>
                                                <div class="recent_cmnt_data">
                                                    <h4><a href="{{ l.get_absolute_url }}">{{ l.title }}</a></h4>
                                                    <span>{{ l.posted | date }}</span>
                                                </div>
                                            </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-9 col-md-9 impl_blog_section">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12">
                                        <div class="impl_blog_box single_blog">
                                            <div class="impl_post_img">
                                                <img src="{{ post_1.image.url }}" alt="blog" class="img-fluid" />
                                                <span class="impl_pst_date">
										{{ post_1.posted | date | truncatechars:9 }}
									</span>
                                            </div>
                                            <div class="impl_post_data">
                                                <h2>{{post_1.title}}</h2>
                                                <p>{{post_1.content|linebreaksbr}}</p>
                                                <div class="impl_pst_info impl_toppadder10">
                                                    <div class="impl_pst_admin">
                                                        <span>{{ post_1.author }} | </span>
                                                        <span>{{ post_1.posted | date }}</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <p><a href="{% url 'blog:blog' %}" class="impl_btn"> Назад </a></p>
                                        </div>
                                        <!--comments area start-->
                                        <div class="comments-area">
                                        	{% if comments %}
                                            <div class="comments-area-title">
                                                <h3 class="comments-title">Комментарии</h3>
                                            </div>
                                            
                                            <ol class="commentlist">
                                            	{% for comment in comments %}
                                                <li class="comment">
                                                    <div class="impl_comments">
                                                        <div class="comment_img">
                                                            <img src="{% static 'app/images/noimage.png' %}" width="100" height="100" alt="img">
                                                        </div>
                                                        <div class="comment_data">
                                                            <div class="comment_data_info">
                                                                <h3>{{comment.author}}</h3>
                                                                <p class="cmnt_date">{{comment.date}}</p>
                                                            </div>
                                                            <p class="comment_para">
                                                                {{comment.text|linebreaksbr}}
                                                            </p>
                                                        </div>
                                                    </div>
                                                </li>
                                                {% endfor %}
                                            </ol>
                                            {% else %}
                                            <h3 id="reply-title" class="comments-title">Комментарии отсутствуют</h3>
                                            <br /><br />
                                            {% endif %}
                                        </div>
                                        {% if user.is_authenticated %}
                                        <div class="comment-respond">
                                            <h3 id="reply-title" class="comments-title">Оставить комментарий</h3>
                                            <form method="POST">
                                            	{% csrf_token %}
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12">
                                                        <div class="comment_input_wrapper">
                                                            {{ form.text }}
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-12 col-md-12">
                                                        <div class="comment-form-submit">
                                                            <input name="submit" type="submit" id="comment-submit" class="submit impl_btn" value="Отправить">
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                        {% else %}
    									<h3 id="reply-title" class="comments-title"> Для добавления своего комментария, пожалуйста, авторизуйтесь.</h3>
										{% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/newpost.html
{% extends "app/layout.html" %}
{% load staticfiles %}
{% block content %}
<div class="impl_bread_wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1>Добавить статью</h1>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                        <li class="breadcrumb-item active">Новая статья</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="impl_blog_wrapper impl_blog_page">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="impl_blog_inner">
                        <div class="row">
                            <div class="col-lg-3 col-md-3">
                                <div class="impl_sidebar">
                                    <div class="widget widget_recent_entries">
                                        <h2 class="widget-title">Последние посты</h2>
                                        <ul>
                                        	{% for l in last %}
                                            <li>
                                                <div class="recent_cmnt_img">
                                                    <img src="{{ l.image.url }}" alt="">
                                                </div>
                                                <div class="recent_cmnt_data">
                                                    <h4><a href="{{ l.get_absolute_url }}">{{ l.title }}</a></h4>
                                                    <span>{{ l.posted | date }}</span>
                                                </div>
                                            </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-9 col-md-9 impl_blog_section">
                                <div class="row">
                                    <div class="col-lg-10 col-md-12 offset-lg-1">
                    <div class="impl_con_form">
                        <div class="contact_map">
                            <div id="contact_map"></div>
                        </div>
                        <div class="col-lg-12 col-md-12">
                            <h1>Заполните все поля</h1>
                        </div>
                        <form method="POST" enctype="multipart/form-data">
                        	{% csrf_token %}
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    {{ blogform.title }}
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    {{ blogform.description }}
                                </div>
                            </div>
                            <div class="col-lg-12 col-md-12">
                                <div class="form-group">
                                    {{ blogform.content }}
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3">
                                <div class="form-group">
                                    {{ blogform.author }}
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3">
                                <div class="form-group">
                                    {{ blogform.image }}
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3">
                                <div class="form-group">
                                    {{ blogform.posted }}
                                </div>
                            </div>
                            <div class="response"></div>
                            <div class="col-lg-12 col-md-12">
                                <input type="hidden" name="form_type" value="contact">
                                <button type="button" class="impl_btn submitForm">Сохранить статью</button>
                            </div>
                        </form>
                    </div>
                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}