cart/urls.py
from . import views
from django.urls import path
from django.conf.urls.static import static

app_name = 'cart'

urlpatterns = [
    path('', views.CartDetail, name='CartDetail'),
    path('remove/(<product_id>)/', views.CartRemove, name='CartRemove'),
    path('add/(<product_id>)/', views.CartAdd, name='CartAdd'),
]

product/urls.py
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from product import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductList, name='ProductList'),
    path('<category_slug>/', views.ProductList, name='ProductListByCategory'),
    path('<slug>', views.ProductDetail, name='ProductDetail'),
]

sto/urls.py
"""
Definition of urls for sto.
"""



from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views
from datetime import datetime
import app.forms
import app.views
from django.shortcuts import render, redirect
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.views.generic import RedirectView


urlpatterns = [
     path('', app.views.home, name='home'),
    path('contact/', app.views.contact, name='contact'),
    path('about/', app.views.about, name='about'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(next_page='/'), name='logout'),
    path('registration/', app.views.registration, name='registration'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('product/', include('product.urls', namespace='product')),
    path('order/', include('order.urls', namespace='order')),
    path('created/', include('order.urls', namespace='created')),
    path('userorders/', app.views.userorders, name='userorders'),
    path('allorders/', app.views.allorders, name='allorders'),
    path('services/', app.views.services, name='services'),
    path('diagnost/', app.views.diagnost, name='diagnost'),
    path('anketa/', app.views.anketa, name='anketa'),
    path('to/', app.views.to, name='to'),
    path('dvs/', app.views.dvs, name='dvs'),
    path('kompl/', app.views.kompl, name='kompl'),
    path('torm/', app.views.torm, name='torm'),
    path('ryl/', app.views.ryl, name='ryl'),
    path('admin/', admin.site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

product/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

# Модель категории
class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True, verbose_name='Имя')
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:ProductListByCategory', args=[self.slug])


# Модель продукта
class Product(models.Model):
    category = models.ForeignKey(Category, on_delete = models.CASCADE, related_name='products', verbose_name="Категория")
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.FileField(blank=True, verbose_name="Изображение товара")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    stock = models.PositiveIntegerField(verbose_name="На складе")
    available = models.BooleanField(default=True, verbose_name="Доступен")
    created = models.DateTimeField(auto_now_add=True, verbose_name='Создан')
    updated = models.DateTimeField(auto_now=True, verbose_name='Обновлен')

    class Meta:
        ordering = ['name']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:ProductDetail', args=[self.slug])

product/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from product.models import Category, Product
from cart.forms import CartAddProductForm
from cart.cart import Cart
from datetime import datetime

# Страница с товарами
def ProductList(request, category_slug=None):
    cart = Cart(request)
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'product/list.html', {
    	'title': 'Все товары',
    	'cart': cart,
        'category': category,
        'categories': categories,
        'products': products,
        'year':datetime.now().year,
    })

# Страница товара
def ProductDetail(request, slug):
    cart = Cart(request)
    product = get_object_or_404(Product, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'product/detail.html',
                             {
                             	'title': 'Товар',
                             	'cart': cart,
                             	'product': product,
                                'cart_product_form': cart_product_form,
                                'year':datetime.now().year,
                             }
                  )

product/templates/product/detail.html
{% extends "app/layout.html" %}
{% load staticfiles %}
{% block content %}
<div class="impl_bread_wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1>{{ product.category }}</h1>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                        <li class="breadcrumb-item"><a href="{% url 'product:ProductList' %}">Каталог</a></li>
                        <li class="breadcrumb-item active">{{ product.name }}</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="impl_blog_wrapper impl_blog_page impl_rightsidebar">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="impl_blog_inner">
                        <div class="row">
                            <div class="col-lg-4 col-md-4 impl_blog_section impl_right_blog">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12">
                                        <div class="impl_blog_box">
                                            <div class="impl_post_img">
                                                <img src="{{ product.image.url }}" height="230" width="300" alt="prod" class="img-responsive"/>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-4 col-md-4">
                                	<div class="impl_sidebar">
                                	<h3><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h3>
                                	<br />
                                	<p>{{ product.description | linebreaksbr }}</p>
                               	</div>
                            </div>
                            <div class="col-lg-4 col-md-4">
                                <div class="impl_sidebar">
                                	<h3>{{ product.category }}</h3>
                                	<br />
                                	<span>Цена: </span>{{ product.price }} руб.
                                	<br /><br />
                                	<form action="{% url "cart:CartAdd" product.id %}" method="post" class="quantity">
								     {{ cart_product_form }}
								     {% csrf_token %}
								     <br /><br />
								     {% if user.is_authenticated %}
								     <button type="submit" name="next" class="next action-button impl_btn" value="Next" >В корзину</button>
								     {% else %}
								   </form>
								   <h6>Войдите для добавления товара в корзину</h6>
								     <br /><br />
								     <button class="next action-button impl_btn justify-center"><a href="{% url 'login' %}">Войти</a></button>
								     {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/list.html
{% extends 'app/layout.html' %}
{% load staticfiles %}

{% block title %}
  {% if category %} {{ category.name }} {% else %} Страница товаров {% endif %}
{% endblock %}

{% block content %}
<div class="impl_bread_wrapper">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <h1>Каталог</h1>
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{% url 'home' %}">Главная</a></li>
                        <li class="breadcrumb-item active">Список товаров</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="impl_blog_wrapper impl_blog_page">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="impl_blog_inner">
                        <div class="row">
                            <div class="col-lg-3 col-md-3">
                                <div class="impl_sidebar">
                                    <div class="widget widget_categories">
                                        <h2 class="widget-title">Категории</h2>
                                        <ul>
                                            <li {% if not category %} class="selected" {% endif %}>
									            <a href="{% url "product:ProductList" %}">Все</a>
									        </li>
									    {% for cat in categories %}
									        <li {% if category.slug == cat.slug %} class="selected" {% endif %}>
									            <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
									        </li>
									    {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-9 col-md-9 impl_blog_section">
                                <div class="row">
                                    <div class="col-lg-12 col-md-12">
    								   <div class="container">
    								       <div class="row">
    								       	{% for product in products %}
    								           <div class="col-lg-6 col-md-6">
    								               <div class="impl_fea_car_box">
    								                   <div class="impl_fea_car_img">
    								                       <img src="{{ product.image.url }}" alt="prod" class="img-fluid impl_frst_car_img" />
    								                       <img src="{{ product.image.url }}" alt="prod" class="img-fluid impl_hover_car_img" />
    								                   </div>
    								                   <div class="impl_fea_car_data">
    								                       <h6><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h6>
    								                       <br /><br />
    								                       <div class="impl_fea_btn">
    								                           <button class="impl_btn"><a href="{{ product.get_absolute_url }}"><span class="impl_doller">{{ product.price }} руб. </span><span class="impl_bnw">Просмотр</span></a></button>
    								                       </div>
    								                   </div>
    								               </div>
    								           </div>
    								           {% endfor %}
    								       </div>
    								   </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}